/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medframe.view;

import java.util.Iterator;
import java.util.List;

/**
 *
 * @author Julia
 */
public class DrugPanel extends javax.swing.JPanel
{
    private String [] drugs = {};
    private String [] doses ={};

    /**
     * Creates new form drugPanel
     */
    public DrugPanel()
    {
//        drugs = {""};
//        doses = new ArrayList();
        initComponents();
    }
    
    public DrugPanel(List drugs, List doses)
    {
        Iterator it = drugs.iterator();
        while(it.hasNext())
        {
            String o = (String) it.next();
            drugs.add(o);
        }
         it = doses.iterator();
        while(it.hasNext())
        {
            String o = (String) it.next();
            doses.add(o);
        }
//        this.drugs = drugs;
//        this.doses = doses;
        
        initComponents();      
        
    }
    
//    private void addProperties()
//    {
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents()
    {

        drugsBox = new javax.swing.JComboBox(drugs);
        doseBox = new javax.swing.JComboBox(doses);
        additDoseField = new javax.swing.JTextField();

        drugsBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                drugsBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(drugsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(additDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(drugsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(doseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(additDoseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drugsBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_drugsBoxActionPerformed
    {//GEN-HEADEREND:event_drugsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugsBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField additDoseField;
    private javax.swing.JComboBox doseBox;
    private javax.swing.JComboBox drugsBox;
    // End of variables declaration//GEN-END:variables
}
